services:

    app.apiaccess.command:
        class: ContaoBayern\NuligadataBundle\Command\AccessApiCommand
        public: true
        tags: ['console.command']
        calls:
          - ["setFramework", ["@contao.framework"]]
          - ["setContainer", ["@service_container"]]

    nuliga.authenticated.request:
        class: ContaoBayern\NuligadataBundle\NuLiga\Request\AuthenticatedRequest
        arguments:
            - '@service_container'
        public: true
