services:

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ['setContainer', ['@service_container']]

    app.apiaccess.command:
        class: ContaoBayern\NuligadataBundle\Command\AccessApiCommand
        arguments:
            - '@nuliga.authenticated.request'
            - '@monolog.logger.contao'
        public: true
        tags: ['console.command']

    nuliga.authenticated.request:
        class: ContaoBayern\NuligadataBundle\NuLiga\Request\AuthenticatedRequest
        arguments:
            - '@service_container'
            - '@cache.app'
            - '@monolog.logger.contao'
        public: true

    ContaoBayern\NuligadataBundle\Controller\ContentElement\NuligadataTableController:
        tags:
            -
                name: contao.content_element
                category: nuligadata
                renderer: esi
                ### method: getCustomResponse
                ### type: my_custom_type
